framework:
    http_client:
        scoped_clients:
            omdb.api.client:
                base_uri: '%env(OMDB_API_URL)%'
                query:
                    apikey: '%env(OMDB_API_KEY)%'
